---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Make sure we have a {{ sudoes_group }} group"
  group:
    name: "{{ sudoes_group }}"
    state: present

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Allow {{ sudoes_group }} group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ sudoes_group }}'
    line: '%{{ sudoes_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add sudoers users to {{ sudoes_group }} group"
  user:
    name: "{{ item.name }}"
    groups: "{{ sudoes_group }}"
    append: "{{ item.sudouser_append }}"
  with_items: "{{ sudoers }}"